### ISSUE TITLE
minor bug in add_colorbar

### ISSUE THREAD

**Issue by lebedov** [mgeier/python-audio#2]
Small fix for the very useful `add_colorbar()` function in [matplotlib-colorbar.ipynb](/github/mgeier/python-audio/blob/master/plotting/matplotlib-colorbar.ipynb); the `aspect` parameter should be cast to a float so `1/aspect` doesn't evaluate to 0.

**Comment by mgeier** [comment]
Thanks for reporting this!
I've created #3, can you please check if this works for you?

**Comment by lebedov** [comment]
Yes. Thanks!
